### PR TITLE
fixed sorting notices

### PR DESCRIPTION
**Pull request by emnlpstr**
fixed the sorting about notices

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](CONTRIBUTING.md)
- [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

## Fixes

- Fixes #

### CODE REVIEW

**Comment by bfabio** [comment]
@emnlpstr why is this change needed?

**Comment by emnlpstr** [comment]
> @emnlpstr why is this change needed?

because it didn't work, you tried to apply the "reverse()" method but "windows.data" was an object type and I just converted it in array before to apply the "reverse()" method.

**Comment by sebbalex** [comment]
> > @emnlpstr why is this change needed?
> 
> because it didn't work, you tried to apply the "reverse()" method but "windows.data" was an object type and I just converted it in array before to apply the "reverse()" method.

based on the [JSON file](https://raw.githubusercontent.com/teamdigitale/padigitale2026-opendata/main/dati/avvisi-latest.json) `data.windows` is an array.
Said that, I would not do this data manipulation client side, instead, I'd rather correct data from source. JSON file should be already sorted as we want to reflect the "Avvisi" page order.

**Comment by sebbalex** [comment]
> > @emnlpstr why is this change needed?
> 
> because it didn't work, you tried to apply the "reverse()" method but "windows.data" was an object type and I just converted it in array before to apply the "reverse()" method.

based on the [JSON file](https://raw.githubusercontent.com/teamdigitale/padigitale2026-opendata/main/dati/avvisi-latest.json) `data.windows` is an array.
Said that, I would not do this data manipulation client side, instead, I'd rather correct data from source. JSON file should be already sorted as we want to reflect the "Avvisi" page order.

**Comment by sebbalex** [comment]
I'm closing this since is not a client side issue

**Pull request closed without merging**
